# Generated by Django 4.2.23 on 2025-11-18 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_userprofile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('data_ingestor', 'Data Ingestor'), ('register_user', 'Register User'), ('editor_paa', 'Editor PAA'), ('master_paa', 'Master PAA')], default='register_user', max_length=32),
        ),
    ]
