# Generated by Django 4.2.23 on 2025-10-05 21:42

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del Indicador')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('formula', models.TextField(verbose_name='Fórmula o Cálculo')),
                ('unit', models.CharField(max_length=20, verbose_name='Unidad de Medida')),
                ('category', models.CharField(choices=[('disposicion', 'Disposición Final'), ('pesaje', 'Pesaje'), ('general', 'General')], max_length=50, verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Indicador',
                'verbose_name_plural': 'Indicadores',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ReportConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del Reporte')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField(verbose_name='Fecha Inicio')),
                ('end_date', models.DateField(verbose_name='Fecha Fin')),
                ('subsecretaria', models.CharField(blank=True, max_length=100, null=True, verbose_name='Subsecretaría')),
                ('tipo_proceso', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo de Proceso')),
                ('chart_type', models.CharField(choices=[('line', 'Línea'), ('bar', 'Barras'), ('pie', 'Torta'), ('table', 'Tabla')], default='table', max_length=20, verbose_name='Tipo de Visualización')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Configuración de Reporte',
                'verbose_name_plural': 'Configuraciones de Reportes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DynamicReportConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre descriptivo del reporte', max_length=100, verbose_name='Nombre del Reporte')),
                ('description', models.TextField(blank=True, help_text='Descripción opcional del reporte', null=True, verbose_name='Descripción')),
                ('start_year', models.IntegerField(validators=[django.core.validators.MinValueValidator(2020), django.core.validators.MaxValueValidator(2030)], verbose_name='Año de inicio')),
                ('end_year', models.IntegerField(validators=[django.core.validators.MinValueValidator(2020), django.core.validators.MaxValueValidator(2030)], verbose_name='Año de fin')),
                ('concesiones_selected', models.JSONField(default=list, help_text='Lista de nombres de concesiones', verbose_name='Concesiones seleccionadas')),
                ('zonas_selected', models.JSONField(default=list, help_text='Lista de nombres de zonas de descarga', verbose_name='Zonas seleccionadas')),
                ('ases_selected', models.JSONField(default=list, help_text='Lista de nombres de ASEs', verbose_name='ASEs seleccionados')),
                ('servicios_selected', models.JSONField(default=list, help_text='Lista de nombres de servicios', verbose_name='Servicios seleccionados')),
                ('group_by', models.CharField(choices=[('month', 'Mes'), ('concesion', 'Concesión'), ('zona', 'Zona'), ('ase', 'ASE'), ('servicio', 'Servicio')], default='month', max_length=20, verbose_name='Agrupar por')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_public', models.BooleanField(default=False, help_text='Permite que otros usuarios vean este reporte', verbose_name='Reporte público')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_configs', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Configuración de Reporte',
                'verbose_name_plural': 'Configuraciones de Reportes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user'], name='reports_dyn_user_id_ca616e_idx'), models.Index(fields=['is_public'], name='reports_dyn_is_publ_b5ff56_idx'), models.Index(fields=['start_year', 'end_year'], name='reports_dyn_start_y_1b2e91_idx')],
            },
        ),
    ]
