CABECERAS_PESAJE = [
    'FECHA ENTRADA', 'FECHA SALIDA', 'CONSECUTIVO ENTRADA', 'CONSECUTIVO SALIDA', 'PLACA',
    'NUMERO VEHICULO', 'CONCESION', 'MACRORUTA', 'MICRORUTA', 'ASE',
    'SERVICIO', 'ZONA DESCARGA', 'PESO ENTRADA', 'PESO SALIDA', 'PESO RESIDUOS',
    'PERSONAS ENTRADA', 'PERSONAS SALIDA', 'USUARIO ENTRADA', 'USUARIO SALIDA',
    'OBSERVACIONES ENTRADA', 'OBSERVACIONES SALIDA', 'OBSERVACIONES ALERTA TARA',
    'OPCIONES', 'IMAGEN ENTRADA', 'IMAGEN SALIDA'
]
