CABECERAS_PESAJE = [
    'FECHA_ENTRADA', 'FECHA_SALIDA', 'CONSECUTIVO_ENTRADA', 'CONSECUTIVO_SALIDA', 'PLACA',
    'NUMERO_VEHICULO', 'CONCESION', 'MACRORUTA', 'MICRORUTA', 'ASE',
    'SERVICIO', 'ZONA_DESCARGA', 'PESO_ENTRADA', 'PESO_SALIDA', 'PESO_RESIDUOS',
    'PERSONAS_ENTRADA', 'PERSONAS_SALIDA', 'USUARIO_ENTRADA', 'USUARIO_SALIDA',
    'OBSERVACIONES_ENTRADA', 'OBSERVACIONES_SALIDA', 'OBSERVACIONES_ALERTA_TARA',
    'OPCIONES', 'IMAGEN_ENTRADA', 'IMAGEN_SALIDA'
]
