# Generated by Django 4.2.20 on 2025-05-03 04:50

from django.db import migrations, models
import django.db.models.deletion
import ingesta.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroCarga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_archivo_original', models.CharField(max_length=255)),
                ('path_minio', models.CharField(blank=True, max_length=500, null=True)),
                ('fecha_hora_carga', models.DateTimeField(auto_now_add=True)),
                ('subsecretaria_origen', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(choices=[('RECIBIDO', 'Recibido en Django'), ('EN_MINIO', 'Subido a MinIO'), ('PROCESANDO_NIFI', 'Procesando por NiFi'), ('ERROR', 'Error'), ('COMPLETADO', 'Completado')], default='RECIBIDO', max_length=20)),
                ('mensaje_error', models.TextField(blank=True, null=True)),
                ('tipo_proceso', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'ordering': ['-fecha_hora_carga'],
            },
        ),
        migrations.CreateModel(
            name='DisposicionFinal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_entrada', models.DateField(blank=True, null=True)),
                ('hora_entrada', models.TimeField(blank=True, null=True)),
                ('fecha_salida', models.DateField(blank=True, null=True)),
                ('hora_salida', models.TimeField(blank=True, null=True)),
                ('epoch_entrada', models.BigIntegerField(blank=True, null=True)),
                ('epoch_salida', models.BigIntegerField(blank=True, null=True)),
                ('consecutivo_entrada', models.CharField(blank=True, max_length=20, null=True)),
                ('consecutivo_salida', models.CharField(blank=True, max_length=20, null=True)),
                ('placa', models.CharField(blank=True, max_length=20, null=True)),
                ('numero_vehiculo', models.CharField(blank=True, max_length=20, null=True)),
                ('concesion', models.CharField(blank=True, max_length=60, null=True)),
                ('macroruta', models.CharField(blank=True, max_length=10, null=True)),
                ('microruta', models.CharField(blank=True, max_length=10, null=True)),
                ('ase', models.CharField(blank=True, max_length=60, null=True)),
                ('servicio', models.CharField(blank=True, max_length=60, null=True)),
                ('zona_descarga', models.CharField(blank=True, max_length=60, null=True)),
                ('peso_entrada', models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True)),
                ('peso_salida', models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True)),
                ('peso_residuos', models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True)),
                ('personas_entrada', models.IntegerField(blank=True, null=True)),
                ('personas_salida', models.IntegerField(blank=True, null=True)),
                ('usuario_entrada', models.CharField(blank=True, max_length=30, null=True)),
                ('usuario_salida', models.CharField(blank=True, max_length=30, null=True)),
                ('observaciones_entrada', models.CharField(blank=True, max_length=60, null=True)),
                ('observaciones_salida', models.CharField(blank=True, max_length=60, null=True)),
                ('observaciones_alerta_tara', models.CharField(blank=True, max_length=60, null=True)),
                ('opciones', models.CharField(blank=True, max_length=60, null=True)),
                ('imagen_entrada', models.URLField(blank=True, max_length=500, null=True)),
                ('imagen_salida', models.URLField(blank=True, max_length=500, null=True)),
                ('fecha_creacion', models.BigIntegerField(default=ingesta.models.get_current_timestamp)),
                ('fecha_actualizacion', models.BigIntegerField(default=ingesta.models.get_current_timestamp)),
                ('registro_carga', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ingesta.registrocarga')),
            ],
            options={
                'verbose_name': 'Disposición Final',
                'verbose_name_plural': 'Disposiciones Finales',
                'ordering': ['-fecha_entrada', 'consecutivo_entrada'],
                'indexes': [models.Index(fields=['epoch_entrada'], name='ingesta_dis_epoch_e_75ad69_idx'), models.Index(fields=['epoch_salida'], name='ingesta_dis_epoch_s_05a737_idx')],
            },
        ),
    ]
