# Generated by Django 4.2.20 on 2025-04-12 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroCarga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_archivo_original', models.CharField(max_length=255)),
                ('path_minio', models.CharField(blank=True, max_length=500, null=True)),
                ('fecha_hora_carga', models.DateTimeField(auto_now_add=True)),
                ('subsecretaria_origen', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(choices=[('RECIBIDO', 'Recibido en Django'), ('EN_MINIO', 'Subido a MinIO'), ('PROCESANDO_NIFI', 'Procesando por NiFi'), ('ERROR', 'Error'), ('COMPLETADO', 'Completado')], default='RECIBIDO', max_length=20)),
                ('mensaje_error', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-fecha_hora_carga'],
            },
        ),
    ]
