# Generated by Django 4.2.23 on 2025-08-10 22:00

from django.db import migrations, models
import ingesta.models.core.base


class Migration(migrations.Migration):

    dependencies = [
        ('ingesta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZonaDescarga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.BigIntegerField(default=ingesta.models.core.base.get_current_timestamp)),
                ('fecha_actualizacion', models.BigIntegerField(default=ingesta.models.core.base.get_current_timestamp)),
                ('codigo', models.CharField(help_text='Código único de la zona', max_length=20, unique=True)),
                ('nombre', models.CharField(help_text='Nombre oficial de la zona', max_length=100)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción adicional', null=True)),
                ('activo', models.BooleanField(default=True, help_text='Indica si la zona está activa')),
            ],
            options={
                'verbose_name': 'Zona de Descarga',
                'verbose_name_plural': 'Zonas de Descarga',
                'ordering': ['nombre'],
                'indexes': [models.Index(fields=['codigo'], name='ingesta_zon_codigo_a728f6_idx'), models.Index(fields=['activo'], name='ingesta_zon_activo_ca4c30_idx')],
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.BigIntegerField(default=ingesta.models.core.base.get_current_timestamp)),
                ('fecha_actualizacion', models.BigIntegerField(default=ingesta.models.core.base.get_current_timestamp)),
                ('codigo', models.CharField(help_text='Código único del servicio', max_length=20, unique=True)),
                ('nombre', models.CharField(help_text='Nombre oficial del servicio', max_length=100)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción adicional', null=True)),
                ('activo', models.BooleanField(default=True, help_text='Indica si el servicio está activo')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'ordering': ['nombre'],
                'indexes': [models.Index(fields=['codigo'], name='ingesta_ser_codigo_dca941_idx'), models.Index(fields=['activo'], name='ingesta_ser_activo_4a62d8_idx')],
            },
        ),
        migrations.CreateModel(
            name='Concesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.BigIntegerField(default=ingesta.models.core.base.get_current_timestamp)),
                ('fecha_actualizacion', models.BigIntegerField(default=ingesta.models.core.base.get_current_timestamp)),
                ('codigo', models.CharField(help_text='Código único de la concesión', max_length=20, unique=True)),
                ('nombre', models.CharField(help_text='Nombre oficial de la concesión', max_length=100)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción adicional', null=True)),
                ('activo', models.BooleanField(default=True, help_text='Indica si la concesión está activa')),
            ],
            options={
                'verbose_name': 'Concesión',
                'verbose_name_plural': 'Concesiones',
                'ordering': ['nombre'],
                'indexes': [models.Index(fields=['codigo'], name='ingesta_con_codigo_25f32d_idx'), models.Index(fields=['activo'], name='ingesta_con_activo_89bc56_idx')],
            },
        ),
        migrations.CreateModel(
            name='ASE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.BigIntegerField(default=ingesta.models.core.base.get_current_timestamp)),
                ('fecha_actualizacion', models.BigIntegerField(default=ingesta.models.core.base.get_current_timestamp)),
                ('codigo', models.CharField(help_text='Código único del ASE', max_length=20, unique=True)),
                ('nombre', models.CharField(help_text='Nombre oficial del ASE', max_length=100)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción adicional', null=True)),
                ('activo', models.BooleanField(default=True, help_text='Indica si el ASE está activo')),
            ],
            options={
                'verbose_name': 'ASE',
                'verbose_name_plural': 'ASEs',
                'ordering': ['nombre'],
                'indexes': [models.Index(fields=['codigo'], name='ingesta_ase_codigo_d56634_idx'), models.Index(fields=['activo'], name='ingesta_ase_activo_66ac6d_idx')],
            },
        ),
    ]
