# Generated by Django 4.2.20 on 2025-04-15 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingesta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrocarga',
            name='tipo_proceso',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
