# Generated by Django 4.2.23 on 2025-09-09 02:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import ingesta.models.core.base


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ingesta', '0002_zonadescarga_servicio_concesion_ase'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvidenciaCarga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.BigIntegerField(default=ingesta.models.core.base.get_current_timestamp)),
                ('fecha_actualizacion', models.BigIntegerField(default=ingesta.models.core.base.get_current_timestamp)),
                ('nombre_archivo_original', models.CharField(max_length=255)),
                ('path_minio', models.CharField(max_length=500)),
                ('fecha_hora_subida', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('content_type', models.CharField(blank=True, max_length=150, null=True)),
                ('registro_carga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='ingesta.registrocarga')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evidencia de Carga',
                'verbose_name_plural': 'Evidencias de Carga',
                'indexes': [models.Index(fields=['registro_carga'], name='ingesta_evi_registr_fbf56c_idx'), models.Index(fields=['fecha_hora_subida'], name='ingesta_evi_fecha_h_143a86_idx')],
            },
        ),
    ]
