# Generated by Django 4.2.20 on 2025-04-29 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ingesta', '0002_registrocarga_tipo_proceso'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisposicionFinal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('fecha_disposicion', models.DateField()),
                ('tipo_disposicion', models.CharField(choices=[('RELLENO_SANITARIO', 'Relleno Sanitario'), ('INCINERACION', 'Incineración'), ('COMPOSTAJE', 'Compostaje'), ('RECICLAJE', 'Reciclaje'), ('OTRO', 'Otro')], max_length=20)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unidad_medida', models.CharField(default='TONELADAS', max_length=20)),
                ('sitio_disposicion', models.CharField(max_length=200)),
                ('departamento', models.CharField(max_length=100)),
                ('municipio', models.CharField(max_length=100)),
                ('generador', models.CharField(max_length=200)),
                ('nit_generador', models.CharField(max_length=20)),
                ('transportador', models.CharField(max_length=200)),
                ('placa_vehiculo', models.CharField(max_length=10)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En Proceso'), ('COMPLETADO', 'Completado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('usuario_creacion', models.CharField(max_length=100)),
                ('usuario_actualizacion', models.CharField(max_length=100)),
                ('registro_carga', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ingesta.registrocarga')),
            ],
            options={
                'verbose_name': 'Disposición Final',
                'verbose_name_plural': 'Disposiciones Finales',
                'ordering': ['-fecha_disposicion', 'codigo'],
            },
        ),
    ]
