# Generated by Django 4.2.20 on 2025-04-29 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingesta', '0003_disposicionfinal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='disposicionfinal',
            options={'ordering': ['-fecha_entrada', 'consecutivo_entrada'], 'verbose_name': 'Disposición Final', 'verbose_name_plural': 'Disposiciones Finales'},
        ),
        migrations.RenameField(
            model_name='disposicionfinal',
            old_name='observaciones',
            new_name='observaciones_alerta_tara',
        ),
        migrations.RemoveField(
            model_name='disposicionfinal',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='disposicionfinal',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='disposicionfinal',
            name='departamento',
        ),
        migrations.RemoveField(
            model_name='disposicionfinal',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='disposicionfinal',
            name='fecha_disposicion',
        ),
        migrations.RemoveField(
            model_name='disposicionfinal',
            name='generador',
        ),
        migrations.RemoveField(
            model_name='disposicionfinal',
            name='municipio',
        ),
        migrations.RemoveField(
            model_name='disposicionfinal',
            name='nit_generador',
        ),
        migrations.RemoveField(
            model_name='disposicionfinal',
            name='placa_vehiculo',
        ),
        migrations.RemoveField(
            model_name='disposicionfinal',
            name='sitio_disposicion',
        ),
        migrations.RemoveField(
            model_name='disposicionfinal',
            name='tipo_disposicion',
        ),
        migrations.RemoveField(
            model_name='disposicionfinal',
            name='transportador',
        ),
        migrations.RemoveField(
            model_name='disposicionfinal',
            name='unidad_medida',
        ),
        migrations.RemoveField(
            model_name='disposicionfinal',
            name='usuario_actualizacion',
        ),
        migrations.RemoveField(
            model_name='disposicionfinal',
            name='usuario_creacion',
        ),
        migrations.AddField(
            model_name='disposicionfinal',
            name='ase',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='disposicionfinal',
            name='concesion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='disposicionfinal',
            name='consecutivo_entrada',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='disposicionfinal',
            name='consecutivo_salida',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='disposicionfinal',
            name='fecha_entrada',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='disposicionfinal',
            name='fecha_salida',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='disposicionfinal',
            name='imagen_entrada',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='disposicionfinal',
            name='imagen_salida',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='disposicionfinal',
            name='macroruta',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='disposicionfinal',
            name='microruta',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='disposicionfinal',
            name='numero_vehiculo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='disposicionfinal',
            name='observaciones_entrada',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='disposicionfinal',
            name='observaciones_salida',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='disposicionfinal',
            name='opciones',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='disposicionfinal',
            name='personas_entrada',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='disposicionfinal',
            name='personas_salida',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='disposicionfinal',
            name='peso_entrada',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='disposicionfinal',
            name='peso_residuos',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='disposicionfinal',
            name='peso_salida',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='disposicionfinal',
            name='placa',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='disposicionfinal',
            name='servicio',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='disposicionfinal',
            name='usuario_entrada',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='disposicionfinal',
            name='usuario_salida',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='disposicionfinal',
            name='zona_descarga',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
