# Generated by Django 4.2.23 on 2025-01-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingesta', '0003_evidenciacarga'),
    ]

    operations = [
        migrations.AddField(
            model_name='concesion',
            name='categoria',
            field=models.CharField(
                blank=True, 
                help_text='Categoría de la concesión según origen del residuo', 
                max_length=100, 
                null=True
            ),
        ),
        migrations.AddField(
            model_name='servicio',
            name='categoria',
            field=models.CharField(
                blank=True, 
                help_text='Categoría del servicio según tipo de procesamiento', 
                max_length=100, 
                null=True
            ),
        ),
        migrations.AddField(
            model_name='zonadescarga',
            name='categoria',
            field=models.CharField(
                blank=True, 
                help_text='Categoría de la zona de descarga según destino final', 
                max_length=100, 
                null=True
            ),
        ),
        migrations.AddIndex(
            model_name='concesion',
            index=models.Index(fields=['categoria'], name='ingesta_con_categor_a1b2c3_idx'),
        ),
        migrations.AddIndex(
            model_name='servicio',
            index=models.Index(fields=['categoria'], name='ingesta_ser_categor_d4e5f6_idx'),
        ),
        migrations.AddIndex(
            model_name='zonadescarga',
            index=models.Index(fields=['categoria'], name='ingesta_zon_categor_g7h8i9_idx'),
        ),
    ]
