# Generated by Django 4.2.20 on 2025-05-01 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingesta', '0004_alter_disposicionfinal_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='disposicionfinal',
            name='epoch_entrada',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='disposicionfinal',
            name='epoch_salida',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='disposicionfinal',
            name='hora_entrada',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='disposicionfinal',
            name='hora_salida',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='disposicionfinal',
            name='ase',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='disposicionfinal',
            name='concesion',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='disposicionfinal',
            name='consecutivo_entrada',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='disposicionfinal',
            name='consecutivo_salida',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='disposicionfinal',
            name='fecha_entrada',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='disposicionfinal',
            name='fecha_salida',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='disposicionfinal',
            name='imagen_entrada',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='disposicionfinal',
            name='imagen_salida',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='disposicionfinal',
            name='macroruta',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='disposicionfinal',
            name='microruta',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='disposicionfinal',
            name='numero_vehiculo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='disposicionfinal',
            name='observaciones_alerta_tara',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='disposicionfinal',
            name='observaciones_entrada',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='disposicionfinal',
            name='observaciones_salida',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='disposicionfinal',
            name='opciones',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='disposicionfinal',
            name='peso_entrada',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='disposicionfinal',
            name='peso_residuos',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='disposicionfinal',
            name='peso_salida',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='disposicionfinal',
            name='placa',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='disposicionfinal',
            name='servicio',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='disposicionfinal',
            name='usuario_entrada',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='disposicionfinal',
            name='usuario_salida',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='disposicionfinal',
            name='zona_descarga',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddIndex(
            model_name='disposicionfinal',
            index=models.Index(fields=['epoch_entrada'], name='ingesta_dis_epoch_e_75ad69_idx'),
        ),
        migrations.AddIndex(
            model_name='disposicionfinal',
            index=models.Index(fields=['epoch_salida'], name='ingesta_dis_epoch_s_05a737_idx'),
        ),
    ]
