# Generated by Django 4.2.23 on 2025-11-18 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plananualadquisicion',
            name='fecha_estimada_inicio',
            field=models.CharField(choices=[('Enero', 'Enero'), ('Febrero', 'Febrero'), ('Marzo', 'Marzo'), ('Abril', 'Abril'), ('Mayo', 'Mayo'), ('Junio', 'Junio'), ('Julio', 'Julio'), ('Agosto', 'Agosto'), ('Septiembre', 'Septiembre'), ('Octubre', 'Octubre'), ('Noviembre', 'Noviembre'), ('Diciembre', 'Diciembre')], max_length=50, verbose_name='Fecha estimada de inicio de proceso de selección (mes)'),
        ),
        migrations.AlterField(
            model_name='plananualadquisicion',
            name='fecha_estimada_presentacion_ofertas',
            field=models.CharField(choices=[('Enero', 'Enero'), ('Febrero', 'Febrero'), ('Marzo', 'Marzo'), ('Abril', 'Abril'), ('Mayo', 'Mayo'), ('Junio', 'Junio'), ('Julio', 'Julio'), ('Agosto', 'Agosto'), ('Septiembre', 'Septiembre'), ('Octubre', 'Octubre'), ('Noviembre', 'Noviembre'), ('Diciembre', 'Diciembre')], max_length=50, verbose_name='Fecha estimada de presentación de ofertas (mes)'),
        ),
    ]
