# Generated by Django 4.2.23 on 2025-11-18 01:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import ingesta.models.core.base


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('paa', '0002_alter_plananualadquisicion_fecha_estimada_inicio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudPAA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.BigIntegerField(default=ingesta.models.core.base.get_current_timestamp)),
                ('fecha_actualizacion', models.BigIntegerField(default=ingesta.models.core.base.get_current_timestamp)),
                ('tipo_accion', models.CharField(choices=[('crear', 'Crear'), ('modificar', 'Modificar'), ('eliminar', 'Eliminar')], max_length=20, verbose_name='Tipo de acción')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('codigo', models.CharField(blank=True, max_length=20, null=True, verbose_name='Código')),
                ('subdireccion', models.CharField(choices=[('SSF', 'Subdirección de servicios funerarios'), ('RBL', 'Subdirección de RBL'), ('SDF', 'Subdirección de Disposición Final'), ('SAL', 'Subdirección de Asuntos Legales'), ('SA', 'Subdirección de Aprovechamiento'), ('SAP', 'Subdirección de Alumbrado Público'), ('SAF', 'Subdirección Administrativa y Financiera'), ('OCDI', 'Oficina de Control Disciplinario Interno'), ('TIC', 'Oficina de TIC'), ('OCI', 'Oficina control interno'), ('OAP', 'Oficina Asesora de Planeación'), ('OACRI', 'Oficina Asesora de Comunicaciones'), ('DG', 'Dirección General')], max_length=10, verbose_name='Subdirección')),
                ('codigos_unspsc', models.TextField(help_text='Ingrese los códigos UNSPSC separados por punto y coma (;)', verbose_name='Código UNSPSC (cada código separado por ;)')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('fecha_estimada_inicio', models.CharField(choices=[('Enero', 'Enero'), ('Febrero', 'Febrero'), ('Marzo', 'Marzo'), ('Abril', 'Abril'), ('Mayo', 'Mayo'), ('Junio', 'Junio'), ('Julio', 'Julio'), ('Agosto', 'Agosto'), ('Septiembre', 'Septiembre'), ('Octubre', 'Octubre'), ('Noviembre', 'Noviembre'), ('Diciembre', 'Diciembre')], max_length=50, verbose_name='Fecha estimada de inicio de proceso de selección (mes)')),
                ('fecha_estimada_presentacion_ofertas', models.CharField(choices=[('Enero', 'Enero'), ('Febrero', 'Febrero'), ('Marzo', 'Marzo'), ('Abril', 'Abril'), ('Mayo', 'Mayo'), ('Junio', 'Junio'), ('Julio', 'Julio'), ('Agosto', 'Agosto'), ('Septiembre', 'Septiembre'), ('Octubre', 'Octubre'), ('Noviembre', 'Noviembre'), ('Diciembre', 'Diciembre')], max_length=50, verbose_name='Fecha estimada de presentación de ofertas (mes)')),
                ('duracion_contrato_numero', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Duración del contrato (número)')),
                ('duracion_contrato_intervalo', models.CharField(choices=[('dias', 'Días'), ('meses', 'Meses'), ('años', 'Años')], max_length=10, verbose_name='Duración del contrato (intervalo)')),
                ('modalidad_seleccion', models.CharField(choices=[('Solicitud de información a los Proveedores', 'Solicitud de información a los Proveedores'), ('Licitación pública', 'Licitación pública'), ('Licitación pública (Obra pública)', 'Licitación pública (Obra pública)'), ('Concurso de méritos con precalificación (descontinuado)', 'Concurso de méritos con precalificación (descontinuado)'), ('Concurso de méritos abierto (descontinuado)', 'Concurso de méritos abierto (descontinuado)'), ('Concurso de méritos abierto', 'Concurso de méritos abierto'), ('Contratación directa (con ofertas)', 'Contratación directa (con ofertas)'), ('Selección abreviada menor cuantía', 'Selección abreviada menor cuantía'), ('Selección Abreviada de Menor Cuantia sin Manifestacion de Interés', 'Selección Abreviada de Menor Cuantia sin Manifestacion de Interés'), ('Selección abreviada subasta inversa', 'Selección abreviada subasta inversa'), ('Mínima cuantía', 'Mínima cuantía'), ('Contratación régimen especial - Selección de comisionista', 'Contratación régimen especial - Selección de comisionista'), ('Contratación régimen especial - Enajenación de bienes para intermediarios idóneos', 'Contratación régimen especial - Enajenación de bienes para intermediarios idóneos'), ('Contratación régimen especial - Banco multilateral y organismos multilaterales', 'Contratación régimen especial - Banco multilateral y organismos multilaterales'), ('Contratación régimen especial (con ofertas)  - Selección de comisionista', 'Contratación régimen especial (con ofertas)  - Selección de comisionista'), ('Contratación régimen especial (con ofertas)  - Enajenación de bienes para intermediarios idóneos', 'Contratación régimen especial (con ofertas)  - Enajenación de bienes para intermediarios idóneos'), ('Contratación régimen especial (con ofertas)  - Régimen especial', 'Contratación régimen especial (con ofertas)  - Régimen especial'), ('Contratación régimen especial (con ofertas)  - Banco multilateral y organismos multilaterales', 'Contratación régimen especial (con ofertas)  - Banco multilateral y organismos multilaterales'), ('Contratación directa.', 'Contratación directa.'), ('Selección abreviada - acuerdo marco', 'Selección abreviada - acuerdo marco')], max_length=200, verbose_name='Modalidad de selección')),
                ('fuente_recursos', models.CharField(choices=[('Recursos propios', 'Recursos propios'), ('Presupuesto de entidad nacional', 'Presupuesto de entidad nacional'), ('Regalías', 'Regalías'), ('Recursos de crédito', 'Recursos de crédito'), ('SGP - Sistema General de Participaciones', 'SGP - Sistema General de Participaciones'), ('No Aplica', 'No Aplica')], max_length=100, verbose_name='Fuente de los recursos')),
                ('valor_total_estimado', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor total estimado')),
                ('valor_estimado_vigencia_actual', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor estimado en la vigencia actual')),
                ('requiere_vigencias_futuras', models.BooleanField(default=False, verbose_name='¿Se requieren vigencias futuras?')),
                ('estado_solicitud_vigencias_futuras', models.CharField(blank=True, choices=[('NA', 'NA'), ('Solicitadas', 'Solicitadas'), ('Aprobadas', 'Aprobadas')], max_length=20, null=True, verbose_name='Estado de solicitud de vigencias futuras')),
                ('correo_responsable', models.EmailField(max_length=254, verbose_name='Correo electrónico del responsable')),
                ('debe_cumplir_30_porciento_alimentos', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], max_length=2, verbose_name='¿Debe cumplir con invertir mínimo el 30% de los recursos del presupuesto destinados a comprar alimentos, cumpliendo con lo establecido en la Ley 2046 de 2020, reglamentada por el Decreto 248 de 2021?')),
                ('incluye_bienes_servicios_distintos_alimentos', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], max_length=2, verbose_name='¿El contrato incluye el suministro de bienes y servicios distintos a alimentos?')),
                ('tipo_solicitud', models.CharField(choices=[('Nueva', 'Nueva'), ('Modificacion', 'Modificación'), ('Eliminacion', 'Eliminación')], max_length=20, verbose_name='Tipo de solicitud')),
                ('justificacion', models.TextField(verbose_name='Justificación')),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de aprobación/rechazo')),
                ('comentarios_aprobador', models.TextField(blank=True, null=True, verbose_name='Comentarios del aprobador')),
                ('registro_original', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='paa.plananualadquisicion', verbose_name='Registro original')),
                ('usuario_aprobador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_paa_aprobadas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario aprobador')),
                ('usuario_solicitante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_paa_enviadas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario solicitante')),
            ],
            options={
                'verbose_name': 'Solicitud PAA',
                'verbose_name_plural': 'Solicitudes PAA',
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['estado'], name='paa_solicit_estado_defbcc_idx'), models.Index(fields=['tipo_accion'], name='paa_solicit_tipo_ac_b7bfae_idx'), models.Index(fields=['usuario_solicitante'], name='paa_solicit_usuario_6db72d_idx'), models.Index(fields=['registro_original'], name='paa_solicit_registr_2d108e_idx')],
            },
        ),
    ]
